catalog:
  "@ayingott/eslint-config": ^2.0.3
  "@ayingott/prettier-config": ^2.1.4
  "@eslint-react/eslint-plugin": ^1.49.0
  "@tailwindcss/postcss": ^4.1.6
  "@types/node": ^22.15.17
  "@types/react": ^19.1.3
  "@types/react-dom": ^19.1.3
  "@types/stats.js": ^0.17.4
  "@types/three": ^0.176.0
  eslint: ^9.26.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  gsap: ^3.13.0
  lint-staged: ^16.0.0
  next: 15.3.2
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  simple-git-hooks: ^2.13.0
  stats.js: ^0.17.0
  tailwindcss: ^4.1.6
  taze: ^19.1.0
  three: ^0.176.0
  typescript: latest
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - sharp
  - simple-git-hooks
  - unrs-resolver
